pm2 ecosystem 수정 / develop cd 파일 수정 / master cd
boostcamp-2020/Project11-B-Web-FE-Performance-Monitoring-Server pull request #193
Opened 2020-12-15 09:26 UTC by EarlyHail

### 구현의도
- pm2 ecosystem 수정
  .env에서 server 변수로 production | develop 구별하도록 수정

- develop cd 파일 수정
  서버 재부팅 시 pm2를 찾지 못하는 오류 수정
  pm2 start로 서버를 시작할 때 이미 존재하면 reload로 동작하는 방식 이용, 오류 해결

- master cd 파일 생성
  Key 만들어서 secret 등록 수 script 작성

### 기능 흐름도, 클래스 다이어그램(선택사항)
- 

### 사용된 기술(선택사항)
- 

### 리뷰 & 논의사항 & 궁금한점(선택사항)
- master cd 검수 부탁드립니다 ㅠㅠ

2020-12-15 09:42 UTC, junsushin-dev commented on .github/workflows/dev-server-cd.yml
> +        run: ssh develop 'pm2 start ecosystem.config.js'
start 하면 자동을 reload 되는 줄은 처음 알았네요... 배워갑니다!

2020-12-16 01:53 UTC, junsushin-dev requested changes
호진님 pm2 start 부분과 관련하여 변경 필요한 부분이 있는 것 같습니다. 확인 부탁드려요!

2020-12-16 01:53 UTC, junsushin-dev commented on .github/workflows/server-cd.yml
> +        run: ssh master 'pm2 start ecosystem.config.js'
pm2 ecosystem.config.js 파일도 위치가 repos/Project11-B-Web-FE-Performance-Monitoring-Server 디렉토리에 있어서 Install & Build 부분과 동일하게 cd를 한번 해주어야 할 것 같네요! 👽

2020-12-16 01:58 UTC, saeeng approved these changes
수고하셨습니다 👏

2020-12-16 04:16 UTC, junsushin-dev approved these changes

2020-12-16 04:16 UTC, junsushin-dev approved these changes

2020-12-16 04:17 UTC, junsushin-dev commented
수정사항 반영 감사드립니다 호진님! 고생하셨습니다. 🥇

2020-12-16 04:27 UTC, juyoungpark718 approved these changes
정말 고생하셨습니다 👍

2020-12-16 04:28 UTC, merged