project owner 변경 API / get user api / 기타 리팩토링
boostcamp-2020/Project11-B-Web-FE-Performance-Monitoring-Server pull request #98
Opened 2020-12-05 13:08 UTC by EarlyHail

### 구현의도
- Project owner 변경 API
   project의 현재 owner validation, target owner validation후 owner 변경

- 사용자 정보를 얻어오는 api 추가

- Project 삭제 api 의 id 타입 `number` -> `string` 수정

- Project에 user를 추가하는 test api 생성

### 기능 흐름도, 클래스 다이어그램(선택사항)
- 

### 사용된 기술(선택사항)
- 

### 리뷰 & 논의사항 & 궁금한점(선택사항)
-

2020-12-06 02:37 UTC, junsushin-dev approved these changes
저는 토요일 날 뻗어있었는데 작업을 하셨다니 대단합니다. 고생하셨습니다! 👍

2020-12-06 02:37 UTC, junsushin-dev commented on src/routes/auth/router.ts
> +  const controller: any = await controllers();
이쪽 commit은 바로 이전에 올려주신 PR와 커밋이 중복되서 올라온 것 같네요. 아마 conflict이 날 것 같아서 이전 PR은 merge 없이 close 처리하면 될 것 같습니다! 😙

2020-12-06 02:37 UTC, junsushin-dev commented on src/routes/test/controllers/addUsers.ts
> + */
주석을 통해서 테스트 API인 것을 명시해주셔서 감사합니다. 다른 분들이 작업할 때 혼동이 없겠네요!

2020-12-06 02:37 UTC, junsushin-dev commented on src/routes/project/controllers/deleteProject.ts
> +    await Project.deleteOne({ _id: projectId });
이쪽은 soft delete를 하는 것이 더 안전할 수도 있을 것 같습니다. 

1. 만약의 상황에서 사용자가 프로젝트를 복구해서 살리기 원할 수 있을 것 같고
2. 현재 이렇게 삭제할 경우 SQL 처럼 on delete cascade가 보장되지 않아서 정합성이 깨질 수 있을 것 같네요
(예를 들어 User.projects 쪽에서는 projectID가 지워져있지 않다던지 하는 경우가 있을 수 있겠네요)

2020-12-06 04:44 UTC, EarlyHail commented on src/routes/project/controllers/deleteProject.ts
> +    await Project.deleteOne({ _id: projectId });
유저들에서 project를 지워야 한다는걸 생각 못했네요

soft delete를 하면 project를 가져올때마다 체크해줘야하지만 복구 기능이 있고, 삭제가 간단해 질것 같습니다.
hard delete를 하면 말씀하신대로 정합성을 지키기 위해 project의 모든 유저들에게서 project id를 지워주어야 하겠네요

어떤 방법이 좋을지 월요일에 간단하게 이야기해보고 결정하는게 좋을것 같습니다.

2020-12-06 04:50 UTC, EarlyHail commented on src/routes/auth/router.ts
> +  const controller: any = await controllers();
conflict 줄이려고 develop에서 브렌치 만들어서 리팩토링 하고 rebase로 가져와서 작업했는데 생각해보니 그게 그거일것 같네요...
일단 놔두고 월요일에 이거 merge되면 이전 PR은 닫겠습니다

2020-12-06 05:31 UTC, junsushin-dev requested changes
안녕하세요, 호진님. Owner 변경 API 관련해서 프로젝트 생성 API와 로직을 일관성있게 맞출 필요가 있는 것 같습니다. 한번 검토 부탁드려요! 🤩

2020-12-06 05:31 UTC, junsushin-dev commented on src/routes/project/controllers/updateProjectOwner.ts
> +    await Project.update({ _id: projectId }, { owner: targetUserId });
제 Local에서 한번 받아서 테스트해봤는데, owner를 넘기고 나면 현재
1. 새로 지정된 owner가 그대로 users 안에 남아있음
2. 원래 owner가 users로 변경되지 않고 삭제됨

위와 같은 문제가 있는 것 같습니다. 

저희가 권한을 Owner, User(=Member) 두 가지로 하기로 했는데, Owner가 
1. User 이면서 Owner의 권한을 추가적으로 가지는 것인지 e.g (Owner: EarlyHail, User: saeeng, juyoung, EarlyHail)
2. Owner, User 중 한 개의 카테고리에만 속하는지 e.g (Owner: EarlyHail, User: saeeng, juyoung)
정해야 할 것 같습니다. 

현재 프로젝트 생성 API는 owner로만 현재 로그인 된 사용자를 추가하게 되어 있어서, 위에서 1번으로 갈 경우 Owner로 사용자를 추가하면서 User로도 추가해줄 필요가 있고, 만약에 2번으로 갈 경우 Owner 변경 API를 바꿔서 신규 Owner는 User에서 빼주고 예전 Owner는 새로 User에 넣어주어야 할 것 같네요! 😊

2020-12-06 08:32 UTC, junsushin-dev commented on src/routes/project/controllers/updateProjectOwner.ts
> +  try {
이쪽 부분에서 ctx.state.user._id 와 originUserId를 비교해서 owner 권한을 가진 유저로부터 온 요청이 맞는 지 확인하는 logic이 추가되면 좋을 것 같습니다.

2020-12-06 08:33 UTC, junsushin-dev commented on src/routes/auth/router.ts
> +  const controller: any = await controllers();
헉 제가 써놓고 까먹어서 밑에 PR을 리뷰 다 approve 된거 보고 제가 merge 해버렸네요... 죄송합니다 ㅠ ㅜ

2020-12-07 00:48 UTC, EarlyHail commented on src/routes/project/controllers/updateProjectOwner.ts
> +    await Project.update({ _id: projectId }, { owner: targetUserId });
owner 변경하는 기능을 너무 단순하게 생각했네요.... 너무 감사합니다!!!
아마 2번으로 가야할것 같은데... 이것도 project와 같이 간단하게 이야기 해보고 결정하면좋을것 같습니다

2020-12-07 01:18 UTC, junsushin-dev commented on src/routes/project/controllers/updateProjectOwner.ts
> +    await Project.update({ _id: projectId }, { owner: targetUserId });
밑의 2번 정책으로 가기로 하고, 위의 문제 Logic을 보강하기로 결정했습니다.

2020-12-07 01:22 UTC, saeeng approved these changes
수고하셨습니다 👍

2020-12-07 01:27 UTC, juyoungpark718 approved these changes
리펙토링 고생하셨습니다 👍

2020-12-07 01:30 UTC, junsushin-dev commented on src/routes/project/controllers/deleteProject.ts
> +    await Project.deleteOne({ _id: projectId });
회의 결과 Soft delete 하는것으로 결정하였습니다.

2020-12-07 01:37 UTC, junsushin-dev approved these changes

2020-12-07 01:37 UTC, junsushin-dev commented
주말에도 새로운 부분 작업하느라 고생하셨습니다 호진님!

2020-12-07 01:45 UTC, merged